# Generated by Django 3.2.16 on 2024-01-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0002_auto_20240106_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wrapper',
            name='title',
            field=models.CharField(help_text='Уникальное название обёртки, не более\n                             256 символов', max_length=256, verbose_name='Название'),
        ),
    ]
